In [1]:
# Import necessary modules and ignore file warnings
import pandas as pd
import numpy as np
from math import floor
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Shuffle the entire dataset
df = pd.read_csv("export/mx_clean.csv")
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,sex,attention,death,intubated,pneumonia,age,diabetes,epoch,asthma,immunosuppression,hypertension,other_diseases,cardiovascular,obesity,renal_disease,tabaquism,contact,result,care
0,1,0,0,0,2,3,0,0,0,1,1,1,1,0,0,0,0,0,0
1,0,0,0,0,2,2,1,0,0,0,1,0,0,1,1,1,1,1,0
2,0,1,0,2,1,3,0,0,1,0,1,0,0,1,0,0,1,0,2
3,1,0,0,0,1,3,0,1,0,0,0,0,0,1,0,0,1,0,1
4,0,0,0,1,2,0,0,0,0,0,0,0,0,0,0,1,0,0,1

In [3]:
# Split variables
training=floor(0.65*df.shape[0])
evaluation=floor(0.3*df.shape[0])
testing=df.shape[0]-training-evaluation

In [4]:
# Split training data
t1=training+evaluation
t2=training+evaluation+testing
train_df=df[0:training]
eval_df=df[training:t1]
test_df=df[t1:t2]

In [5]:
# Generate Libra compatible schema
schema=[]
for column in df:
    val=df[column].nunique()
    schema.append(val)
print(schema)

[2, 2, 2, 3, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3]

In [6]:
# Save schema to file
sch=pd.DataFrame(data={"col1": schema})
sch=sch.transpose()
sch.head()
sch.to_csv('export/schema.csv',index=False, header=False)

In [7]:
# Save Libra compatible datasets
train_df.to_csv('export/train.csv',index=False, header=False)
eval_df.to_csv('export/eval.csv',index=False, header=False)
test_df.to_csv('export/test.csv',index=False, header=False)